//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :2.0.50727.1433
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDM {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KDM.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;value&gt;
        ///  &lt;struct&gt;
        ///    &lt;member&gt;
        ///      &lt;name&gt;version&lt;/name&gt;
        ///      &lt;value&gt;
        ///        &lt;struct&gt;
        ///          &lt;member&gt;
        ///            &lt;name&gt;hostname&lt;/name&gt;
        ///            &lt;value&gt;cheesy-2&lt;/value&gt;
        ///          &lt;/member&gt;
        ///          &lt;member&gt;
        ///            &lt;name&gt;date&lt;/name&gt;
        ///            &lt;value&gt;2008-11-08&lt;/value&gt;
        ///          &lt;/member&gt;
        ///          &lt;member&gt;
        ///            &lt;name&gt;product_version&lt;/name&gt;
        ///            &lt;value&gt;1.0.0&lt;/value&gt;
        ///          &lt;/member&gt;
        ///          &lt;member&gt;
        ///            &lt;name&gt;product_brand&lt;/name&gt;
        ///            &lt;va [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string XVA_ova_base {
            get {
                return ResourceManager.GetString("XVA_ova_base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à                               &lt;value&gt;{0}&lt;/value&gt;
        ///.
        /// </summary>
        internal static string XVA_ova_ref {
            get {
                return ResourceManager.GetString("XVA_ova_ref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à             &lt;value&gt;
        ///              &lt;struct&gt;
        ///                &lt;member&gt;
        ///                  &lt;name&gt;class&lt;/name&gt;
        ///                  &lt;value&gt;SR&lt;/value&gt;
        ///                &lt;/member&gt;
        ///                &lt;member&gt;
        ///                  &lt;name&gt;id&lt;/name&gt;
        ///                  &lt;value&gt;{0}&lt;/value&gt;
        ///                &lt;/member&gt;
        ///                &lt;member&gt;
        ///                  &lt;name&gt;snapshot&lt;/name&gt;
        ///                  &lt;value&gt;
        ///                    &lt;struct&gt;
        ///                      &lt;member&gt;
        ///                        &lt;name&gt;uuid&lt;/name&gt;
        ///               [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string XVA_ova_sr {
            get {
                return ResourceManager.GetString("XVA_ova_sr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à             &lt;value&gt;
        ///              &lt;struct&gt;
        ///                &lt;member&gt;
        ///                  &lt;name&gt;class&lt;/name&gt;
        ///                  &lt;value&gt;VBD&lt;/value&gt;
        ///                &lt;/member&gt;
        ///                &lt;member&gt;
        ///                  &lt;name&gt;id&lt;/name&gt;
        ///                  &lt;value&gt;{0}&lt;/value&gt;
        ///                &lt;/member&gt;
        ///                &lt;member&gt;
        ///                  &lt;name&gt;snapshot&lt;/name&gt;
        ///                  &lt;value&gt;
        ///                    &lt;struct&gt;
        ///                      &lt;member&gt;
        ///                        &lt;name&gt;uuid&lt;/name&gt;
        ///              [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string XVA_ova_vbd {
            get {
                return ResourceManager.GetString("XVA_ova_vbd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à             &lt;value&gt;
        ///              &lt;struct&gt;
        ///                &lt;member&gt;
        ///                  &lt;name&gt;class&lt;/name&gt;
        ///                  &lt;value&gt;VDI&lt;/value&gt;
        ///                &lt;/member&gt;
        ///                &lt;member&gt;
        ///                  &lt;name&gt;id&lt;/name&gt;
        ///                  &lt;value&gt;{0}&lt;/value&gt;
        ///                &lt;/member&gt;
        ///                &lt;member&gt;
        ///                  &lt;name&gt;snapshot&lt;/name&gt;
        ///                  &lt;value&gt;
        ///                    &lt;struct&gt;
        ///                      &lt;member&gt;
        ///                        &lt;name&gt;uuid&lt;/name&gt;
        ///              [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string XVA_ova_vdi {
            get {
                return ResourceManager.GetString("XVA_ova_vdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à             &lt;value&gt;
        ///              &lt;struct&gt;
        ///                &lt;member&gt;
        ///                  &lt;name&gt;class&lt;/name&gt;
        ///                  &lt;value&gt;VM&lt;/value&gt;
        ///                &lt;/member&gt;
        ///                &lt;member&gt;
        ///                  &lt;name&gt;id&lt;/name&gt;
        ///                  &lt;value&gt;{0}&lt;/value&gt;
        ///                &lt;/member&gt;
        ///                &lt;member&gt;
        ///                  &lt;name&gt;snapshot&lt;/name&gt;
        ///                  &lt;value&gt;
        ///                    &lt;struct&gt;
        ///                      &lt;member&gt;
        ///                        &lt;name&gt;uuid&lt;/name&gt;
        ///               [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string XVA_ova_vm {
            get {
                return ResourceManager.GetString("XVA_ova_vm", resourceCulture);
            }
        }
    }
}
