//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KAVE.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KAVE.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] astnet {
            get {
                object obj = ResourceManager.GetObject("astnet", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p class=&quot;phishing l12n&quot;&gt;{0}&lt;/p&gt;
        ///        &lt;p class=&quot;phishing google&quot;&gt;
        ///if you want to continue navigating to this website  you need to disable Kavprot smart security Web protection.
        ///        &lt;/p&gt;
        ///          &lt;div class=&quot;button-bar&quot; id=&quot;button-bar&quot;&gt;
        ///  
        ///        &lt;/div&gt;
        ///    &lt;/div&gt;
        ///&lt;/div&gt;
        ///
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string Body {
            get {
                return ResourceManager.GetString("Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;alert&quot; class=&quot;alert phishing google&quot;&gt;
        ///    &lt;h1 class=&quot;phishing&quot;&gt;&lt;span class=&quot;l12n size-font-to-fit&quot;&gt;{0}&lt;/span&gt;&lt;/h1&gt;
        ///       &lt;div class=&quot;alert-body&quot;&gt;.
        /// </summary>
        internal static string Bodytitle {
            get {
                return ResourceManager.GetString("Bodytitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;content-type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;.
        /// </summary>
        internal static string ErrorPageHead {
            get {
                return ResourceManager.GetString("ErrorPageHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Handle.exe&gt; Handles.txt.
        /// </summary>
        internal static string HANDLE {
            get {
                return ResourceManager.GetString("HANDLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning- Visiting this web site may harm your computer. This page appears to contain malicious code that could be downloaded to your computer without your consent. You can learn more about harmful web content including viruses and other malicious code and how to protect your computer at &lt;a href=&quot;http://StopBadware.org&quot;&gt;STOP BADWARE&lt;/a&gt;..
        /// </summary>
        internal static string MalwareMessage {
            get {
                return ResourceManager.GetString("MalwareMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning- Suspected phishing page. This page may be a forgery or imitation of another website, designed to trick users into sharing personal or financial information. Entering any personal information on this page may result in identity theft or other abuse. You can find out more about phishing from &lt;a href=&quot;http://www.antiphishing.org&quot;&gt;http://www.antiphishing.org&lt;/a&gt;..
        /// </summary>
        internal static string PhishMessage {
            get {
                return ResourceManager.GetString("PhishMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning- Suspected porn page. This page is reported as a porn page or blocked by the Parental Control. Visiting this website is very dangerous..
        /// </summary>
        internal static string PornMSG {
            get {
                return ResourceManager.GetString("PornMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;style&gt;
        ///    * {
        ///        -webkit-box-sizing: border-box;
        ///    }
        ///
        ///    html {
        ///        display: table;
        ///        height: 100%;
        ///        width: 100%;
        ///        background-color: rgba(0, 0, 0, 0.7);
        ///    }
        ///
        ///    body {
        ///        background-composite: copy;
        ///        display: table-cell;
        ///        vertical-align: middle;
        ///        margin: 0;
        ///        padding: 20px;
        ///       user-select: none;
        ///       text-size-adjust: none;
        ///        cursor: default;
        ///    }
        ///
        ///    .alert {
        ///        position: relative;
        ///        width [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Ressources {
            get {
                return ResourceManager.GetString("Ressources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Root {
            get {
                object obj = ResourceManager.GetObject("Root", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap S {
            get {
                object obj = ResourceManager.GetObject("S", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SSL {
            get {
                object obj = ResourceManager.GetObject("SSL", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;title&gt;{0}&lt;/title&gt;.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Pages apears if you : &lt;ul&gt;&lt;li&gt;Removed the Web Virus database  from DB directory.&lt;/li&gt;&lt;li&gt;Blocked The Network&lt;/li&gt;&lt;/ul&gt;.
        /// </summary>
        internal static string UnderterminedMSG {
            get {
                return ResourceManager.GetString("UnderterminedMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap warning_black {
            get {
                object obj = ResourceManager.GetObject("warning_black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
